"""Curated movie catalog for offline seeding (no OMDb API required)."""

SEED_MOVIES = [
    # --- Sci-Fi ---
    {
        "imdb_id": "tt0133093",
        "title": "The Matrix",
        "year": "1999",
        "rated": "R",
        "runtime": "136 min",
        "genres": ["Action", "Sci-Fi"],
        "director": "Lana Wachowski",
        "actors": ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss", "Hugo Weaving"],
        "plot": "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.",
        "poster": "https://m.media-amazon.com/images/M/MV5BN2NmN2VhMTQtMDNiOS00NDlhLTliMjgtODE2ZDYxZjlhYjVjXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "8.7",
        "imdb_votes": "2,100,000",
    },
    {
        "imdb_id": "tt0816692",
        "title": "Interstellar",
        "year": "2014",
        "rated": "PG-13",
        "runtime": "169 min",
        "genres": ["Adventure", "Drama", "Sci-Fi"],
        "director": "Christopher Nolan",
        "actors": ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine"],
        "plot": "When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.",
        "poster": "https://m.media-amazon.com/images/M/MV5BYzdjMDAxZGItMjI2My00ODA1LTlkNzItOWFjMDU5ZDJlYWY3XkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "8.7",
        "imdb_votes": "2,100,000",
    },
    {
        "imdb_id": "tt0083658",
        "title": "Blade Runner",
        "year": "1982",
        "rated": "R",
        "runtime": "117 min",
        "genres": ["Action", "Drama", "Sci-Fi"],
        "director": "Ridley Scott",
        "actors": ["Harrison Ford", "Rutger Hauer", "Sean Young", "Daryl Hannah"],
        "plot": "A blade runner must pursue and terminate four replicants who stole a ship in space and have returned to Earth to find their creator.",
        "poster": "https://m.media-amazon.com/images/M/MV5BOGE5MWMxMGEtMzBmMS00NTBmLWIxNDctNmRiMjU2YjkzNjI0XkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "8.1",
        "imdb_votes": "850,000",
    },
    {
        "imdb_id": "tt1375666",
        "title": "Inception",
        "year": "2010",
        "rated": "PG-13",
        "runtime": "148 min",
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "director": "Christopher Nolan",
        "actors": ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page", "Tom Hardy"],
        "plot": "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.",
        "poster": "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg",
        "imdb_rating": "8.8",
        "imdb_votes": "2,500,000",
    },
    {
        "imdb_id": "tt0076759",
        "title": "Star Wars: Episode IV - A New Hope",
        "year": "1977",
        "rated": "PG",
        "runtime": "121 min",
        "genres": ["Action", "Adventure", "Fantasy"],
        "director": "George Lucas",
        "actors": ["Mark Hamill", "Harrison Ford", "Carrie Fisher", "Alec Guinness"],
        "plot": "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station, while also attempting to rescue Princess Leia.",
        "poster": "https://m.media-amazon.com/images/M/MV5BOGUwMDk0Y2MtNjBlNi00NmRiLTk2MWYtMGMyMDlhYmI4ZDBjXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "8.6",
        "imdb_votes": "1,500,000",
    },
    {
        "imdb_id": "tt0088763",
        "title": "Back to the Future",
        "year": "1985",
        "rated": "PG",
        "runtime": "116 min",
        "genres": ["Adventure", "Comedy", "Sci-Fi"],
        "director": "Robert Zemeckis",
        "actors": ["Michael J. Fox", "Christopher Lloyd", "Lea Thompson", "Crispin Glover"],
        "plot": "Marty McFly, a 17-year-old high school student, is accidentally sent 30 years into the past in a time-traveling DeLorean invented by his close friend, the maverick scientist Doc Brown.",
        "poster": "https://m.media-amazon.com/images/M/MV5BZmU0M2Y1OGUtZjIxNi00ZjBkLTg1MjgtOWIyNThiZWIwYjRiXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "8.5",
        "imdb_votes": "1,300,000",
    },
    {
        "imdb_id": "tt2543164",
        "title": "Arrival",
        "year": "2016",
        "rated": "PG-13",
        "runtime": "116 min",
        "genres": ["Drama", "Mystery", "Sci-Fi"],
        "director": "Denis Villeneuve",
        "actors": ["Amy Adams", "Jeremy Renner", "Forest Whitaker", "Michael Stuhlbarg"],
        "plot": "A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world.",
        "poster": "https://m.media-amazon.com/images/M/MV5BMTExMzU0ODcxNDheQTJeQWpwZ15BbWU4MDE1OTI4MzAy._V1_SX300.jpg",
        "imdb_rating": "7.9",
        "imdb_votes": "750,000",
    },
    {
        "imdb_id": "tt0078748",
        "title": "Alien",
        "year": "1979",
        "rated": "R",
        "runtime": "117 min",
        "genres": ["Horror", "Sci-Fi"],
        "director": "Ridley Scott",
        "actors": ["Sigourney Weaver", "Tom Skerritt", "John Hurt", "Veronica Cartwright"],
        "plot": "The crew of a commercial spacecraft encounter a deadly lifeform after investigating an unknown transmission.",
        "poster": "https://m.media-amazon.com/images/M/MV5BOGQzZTBjMjQtOTVmMS00NGE5LWEyYmMtOGQ1ZGZjNmRkYjFhXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "8.5",
        "imdb_votes": "950,000",
    },
    # --- Drama ---
    {
        "imdb_id": "tt0111161",
        "title": "The Shawshank Redemption",
        "year": "1994",
        "rated": "R",
        "runtime": "142 min",
        "genres": ["Drama"],
        "director": "Frank Darabont",
        "actors": ["Tim Robbins", "Morgan Freeman", "Bob Gunton", "William Sadler"],
        "plot": "Over the course of several years, two convicts form a friendship, seeking consolation and, eventually, redemption through basic compassion.",
        "poster": "https://m.media-amazon.com/images/M/MV5BMDAyY2FhYjctNDc5OS00MDNlLThiMGUtY2UxYWVkNGY2ZjljXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "9.3",
        "imdb_votes": "2,900,000",
    },
    {
        "imdb_id": "tt0068646",
        "title": "The Godfather",
        "year": "1972",
        "rated": "R",
        "runtime": "175 min",
        "genres": ["Crime", "Drama"],
        "director": "Francis Ford Coppola",
        "actors": ["Marlon Brando", "Al Pacino", "James Caan", "Robert Duvall"],
        "plot": "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant youngest son.",
        "poster": "https://m.media-amazon.com/images/M/MV5BYTJkNGQyZDgtZDQ0NC00MDM0LWEzZWQtYzUzZDEwMDljZWNjXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "9.2",
        "imdb_votes": "2,000,000",
    },
    {
        "imdb_id": "tt0109830",
        "title": "Forrest Gump",
        "year": "1994",
        "rated": "PG-13",
        "runtime": "142 min",
        "genres": ["Drama", "Romance"],
        "director": "Robert Zemeckis",
        "actors": ["Tom Hanks", "Robin Wright", "Gary Sinise", "Sally Field"],
        "plot": "The history of the United States from the 1950s to the '70s unfolds from the perspective of an Alabama man with an IQ of 75, who yearns to be reunited with his childhood sweetheart.",
        "poster": "https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNjU1NjMzXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "8.8",
        "imdb_votes": "2,200,000",
    },
    {
        "imdb_id": "tt0108052",
        "title": "Schindler's List",
        "year": "1993",
        "rated": "R",
        "runtime": "195 min",
        "genres": ["Biography", "Drama", "History"],
        "director": "Steven Spielberg",
        "actors": ["Liam Neeson", "Ralph Fiennes", "Ben Kingsley", "Caroline Goodall"],
        "plot": "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
        "poster": "https://m.media-amazon.com/images/M/MV5BNjM1ZDQxYWUtMzQyZS00MTE1LWJmZGYtNGUyNTdlYjM3ZmVmXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "9.0",
        "imdb_votes": "1,500,000",
    },
    {
        "imdb_id": "tt0407887",
        "title": "The Departed",
        "year": "2006",
        "rated": "R",
        "runtime": "151 min",
        "genres": ["Crime", "Drama", "Thriller"],
        "director": "Martin Scorsese",
        "actors": ["Leonardo DiCaprio", "Matt Damon", "Jack Nicholson", "Mark Wahlberg"],
        "plot": "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.",
        "poster": "https://m.media-amazon.com/images/M/MV5BMTI1MTY2OTIxNV5BMl5BanBnXkFtZTYwNjQ4NjY3._V1_SX300.jpg",
        "imdb_rating": "8.5",
        "imdb_votes": "1,400,000",
    },
    {
        "imdb_id": "tt0120689",
        "title": "The Green Mile",
        "year": "1999",
        "rated": "R",
        "runtime": "189 min",
        "genres": ["Crime", "Drama", "Fantasy"],
        "director": "Frank Darabont",
        "actors": ["Tom Hanks", "Michael Clarke Duncan", "David Morse", "Bonnie Hunt"],
        "plot": "A tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
        "poster": "https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_SX300.jpg",
        "imdb_rating": "8.6",
        "imdb_votes": "1,400,000",
    },
    # --- Action / Thriller ---
    {
        "imdb_id": "tt0468569",
        "title": "The Dark Knight",
        "year": "2008",
        "rated": "PG-13",
        "runtime": "152 min",
        "genres": ["Action", "Crime", "Drama"],
        "director": "Christopher Nolan",
        "actors": ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Michael Caine"],
        "plot": "When a menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman, James Gordon and Harvey Dent must work together to put an end to the madness.",
        "poster": "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg",
        "imdb_rating": "9.0",
        "imdb_votes": "2,900,000",
    },
    {
        "imdb_id": "tt0137523",
        "title": "Fight Club",
        "year": "1999",
        "rated": "R",
        "runtime": "139 min",
        "genres": ["Drama"],
        "director": "David Fincher",
        "actors": ["Brad Pitt", "Edward Norton", "Meat Loaf", "Zach Grenier"],
        "plot": "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
        "poster": "https://m.media-amazon.com/images/M/MV5BOTgyOGQ1NDItNGU3Ny00MjU3LTg2YWEtNmEyYjBiMjI1Y2M5XkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "8.8",
        "imdb_votes": "2,300,000",
    },
    {
        "imdb_id": "tt0110912",
        "title": "Pulp Fiction",
        "year": "1994",
        "rated": "R",
        "runtime": "154 min",
        "genres": ["Crime", "Drama"],
        "director": "Quentin Tarantino",
        "actors": ["John Travolta", "Uma Thurman", "Samuel L. Jackson", "Bruce Willis"],
        "plot": "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
        "poster": "https://m.media-amazon.com/images/M/MV5BYTViYTE3ZGQtNDBlMC00ZTAyLTkyODMtZGRiZDg0MjA2YThkXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "8.9",
        "imdb_votes": "2,200,000",
    },
    {
        "imdb_id": "tt0167260",
        "title": "The Lord of the Rings: The Return of the King",
        "year": "2003",
        "rated": "PG-13",
        "runtime": "201 min",
        "genres": ["Action", "Adventure", "Drama"],
        "director": "Peter Jackson",
        "actors": ["Elijah Wood", "Viggo Mortensen", "Ian McKellen", "Orlando Bloom"],
        "plot": "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
        "poster": "https://m.media-amazon.com/images/M/MV5BMTZkMjBjNWMtZGI5OC00MGU0LTk4ZTItODg2NWM3NTVmNWQ4XkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "9.0",
        "imdb_votes": "2,000,000",
    },
    {
        "imdb_id": "tt1392190",
        "title": "Mad Max: Fury Road",
        "year": "2015",
        "rated": "R",
        "runtime": "120 min",
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "director": "George Miller",
        "actors": ["Tom Hardy", "Charlize Theron", "Nicholas Hoult", "Zoë Kravitz"],
        "plot": "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper and a drifter named Max.",
        "poster": "https://m.media-amazon.com/images/M/MV5BN2EwM2I5OWMtMGQyMi00Zjg1LWJkNTctZTdjYTA4OGUwZjMyXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "8.1",
        "imdb_votes": "1,100,000",
    },
    {
        "imdb_id": "tt0172495",
        "title": "Gladiator",
        "year": "2000",
        "rated": "R",
        "runtime": "155 min",
        "genres": ["Action", "Adventure", "Drama"],
        "director": "Ridley Scott",
        "actors": ["Russell Crowe", "Joaquin Phoenix", "Connie Nielsen", "Oliver Reed"],
        "plot": "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
        "poster": "https://m.media-amazon.com/images/M/MV5Bijk4YzYzMzktMzY5Zi00YjA0LThlZTktMmNmNGRhOGIwMGE4XkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "8.5",
        "imdb_votes": "1,600,000",
    },
    # --- Horror / Thriller ---
    {
        "imdb_id": "tt0081505",
        "title": "The Shining",
        "year": "1980",
        "rated": "R",
        "runtime": "146 min",
        "genres": ["Drama", "Horror"],
        "director": "Stanley Kubrick",
        "actors": ["Jack Nicholson", "Shelley Duvall", "Danny Lloyd", "Scatman Crothers"],
        "plot": "A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence, while his psychic son sees horrific forebodings from both past and future.",
        "poster": "https://m.media-amazon.com/images/M/MV5BZWFlYmY2MGEtZjVkYS00YzU4LTg0YjQtYzY1ZGE3NTA5NGQxXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "8.4",
        "imdb_votes": "1,100,000",
    },
    {
        "imdb_id": "tt6751668",
        "title": "Parasite",
        "year": "2019",
        "rated": "R",
        "runtime": "132 min",
        "genres": ["Comedy", "Drama", "Thriller"],
        "director": "Bong Joon Ho",
        "actors": ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong", "Choi Woo-shik"],
        "plot": "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
        "poster": "https://m.media-amazon.com/images/M/MV5BYjk1Y2U4MjQtY2ZiNS00OWQyLWI3MmYtZWUwNmRjYWRiNWNhXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "8.5",
        "imdb_votes": "900,000",
    },
    {
        "imdb_id": "tt5052448",
        "title": "Get Out",
        "year": "2017",
        "rated": "R",
        "runtime": "104 min",
        "genres": ["Horror", "Mystery", "Thriller"],
        "director": "Jordan Peele",
        "actors": ["Daniel Kaluuya", "Allison Williams", "Bradley Whitford", "Catherine Keener"],
        "plot": "A young African-American visits his white girlfriend's parents for the weekend, where his simmering uneasiness about their reception of him eventually reaches a boiling point.",
        "poster": "https://m.media-amazon.com/images/M/MV5BMjUxMDQwNjcyNl5BMl5BanBnXkFtZTgwNzcwMzc0MTI@._V1_SX300.jpg",
        "imdb_rating": "7.8",
        "imdb_votes": "650,000",
    },
    {
        "imdb_id": "tt0102926",
        "title": "The Silence of the Lambs",
        "year": "1991",
        "rated": "R",
        "runtime": "118 min",
        "genres": ["Crime", "Drama", "Thriller"],
        "director": "Jonathan Demme",
        "actors": ["Jodie Foster", "Anthony Hopkins", "Lawrence A. Bonney", "Kasi Lemmons"],
        "plot": "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.",
        "poster": "https://m.media-amazon.com/images/M/MV5BNjNhZTk0ZmEtNjJhMi00YzFlLWE1MmEtYzM1M2ZmMGMwMTU4XkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "8.6",
        "imdb_votes": "1,500,000",
    },
    # --- Comedy / Romance ---
    {
        "imdb_id": "tt0211915",
        "title": "Amélie",
        "year": "2001",
        "rated": "R",
        "runtime": "122 min",
        "genres": ["Comedy", "Romance"],
        "director": "Jean-Pierre Jeunet",
        "actors": ["Audrey Tautou", "Mathieu Kassovitz", "Rufus", "Lorella Cravotta"],
        "plot": "Amélie is an innocent and naive girl in Paris with her own sense of justice. She decides to help those around her and, along the way, discovers love.",
        "poster": "https://m.media-amazon.com/images/M/MV5BNDg4NjM1YjMtYmNhZC00MjM0LWFiZmMtNGY1Y2YxNGIzOWM3XkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "8.3",
        "imdb_votes": "770,000",
    },
    {
        "imdb_id": "tt0118799",
        "title": "Life Is Beautiful",
        "year": "1997",
        "rated": "PG-13",
        "runtime": "116 min",
        "genres": ["Comedy", "Drama", "Romance"],
        "director": "Roberto Benigni",
        "actors": ["Roberto Benigni", "Nicoletta Braschi", "Giorgio Cantarini", "Giustino Durano"],
        "plot": "When an open-minded Jewish waiter and his son become victims of the Holocaust, he uses a perfect mixture of will, humor and imagination to protect his son from the dangers around their camp.",
        "poster": "https://m.media-amazon.com/images/M/MV5BYmJmM2Q4NmMtYThmNC00ZjRlLWEyZmItZTIwOTBlZDQ3NTQ1XkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "8.6",
        "imdb_votes": "730,000",
    },
    {
        "imdb_id": "tt0338013",
        "title": "Eternal Sunshine of the Spotless Mind",
        "year": "2004",
        "rated": "R",
        "runtime": "108 min",
        "genres": ["Drama", "Romance", "Sci-Fi"],
        "director": "Michel Gondry",
        "actors": ["Jim Carrey", "Kate Winslet", "Tom Wilkinson", "Gerry Robert Byrne"],
        "plot": "When their relationship turns sour, a couple undergoes a medical procedure to have each other erased from their memories forever.",
        "poster": "https://m.media-amazon.com/images/M/MV5BMTY4NzcwODg3Nl5BMl5BanBnXkFtZTcwNTEwOTMyMw@@._V1_SX300.jpg",
        "imdb_rating": "8.3",
        "imdb_votes": "1,100,000",
    },
    {
        "imdb_id": "tt0071562",
        "title": "The Godfather Part II",
        "year": "1974",
        "rated": "R",
        "runtime": "202 min",
        "genres": ["Crime", "Drama"],
        "director": "Francis Ford Coppola",
        "actors": ["Al Pacino", "Robert De Niro", "Robert Duvall", "Diane Keaton"],
        "plot": "The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.",
        "poster": "https://m.media-amazon.com/images/M/MV5BNzc1OWY5MjktZDllMi00ZDEzLWEwMGItYjk1YmRhYjBjNTVlXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "9.0",
        "imdb_votes": "1,400,000",
    },
    # --- Animation ---
    {
        "imdb_id": "tt0910970",
        "title": "WALL·E",
        "year": "2008",
        "rated": "G",
        "runtime": "98 min",
        "genres": ["Animation", "Adventure", "Family"],
        "director": "Andrew Stanton",
        "actors": ["Ben Burtt", "Elissa Knight", "Jeff Garlin", "Fred Willard"],
        "plot": "In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind.",
        "poster": "https://m.media-amazon.com/images/M/MV5BMjExMTg5OTU0NF5BMl5BanBnXkFtZTcwMjMxMzMzMw@@._V1_SX300.jpg",
        "imdb_rating": "8.4",
        "imdb_votes": "1,100,000",
    },
    {
        "imdb_id": "tt0245429",
        "title": "Spirited Away",
        "year": "2001",
        "rated": "PG",
        "runtime": "125 min",
        "genres": ["Animation", "Adventure", "Family"],
        "director": "Hayao Miyazaki",
        "actors": ["Daveigh Chase", "Suzanne Pleshette", "Miyu Irino", "Rumi Hiiragi"],
        "plot": "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches and spirits, and where humans are changed into beasts.",
        "poster": "https://m.media-amazon.com/images/M/MV5BMjlmZmI5MDctNDE2YS00YWE0LWE5ZWItZDBhYWQ0NTcxNWRhXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "8.6",
        "imdb_votes": "850,000",
    },
    {
        "imdb_id": "tt2380307",
        "title": "Coco",
        "year": "2017",
        "rated": "PG",
        "runtime": "105 min",
        "genres": ["Animation", "Adventure", "Drama"],
        "director": "Lee Unkrich",
        "actors": ["Anthony Gonzalez", "Gael García Bernal", "Benjamin Bratt", "Alanna Ubach"],
        "plot": "Aspiring musician Miguel, confronted with his family's ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather, a legendary singer.",
        "poster": "https://m.media-amazon.com/images/M/MV5BYjQ5NjM0Y2YtNjZkNC00ZDhkLWJjMWItN2QyNzFkMDE3ZjAxXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "8.4",
        "imdb_votes": "550,000",
    },
    {
        "imdb_id": "tt2096673",
        "title": "Inside Out",
        "year": "2015",
        "rated": "PG",
        "runtime": "95 min",
        "genres": ["Animation", "Adventure", "Comedy"],
        "director": "Pete Docter",
        "actors": ["Amy Poehler", "Bill Hader", "Lewis Black", "Mindy Kaling"],
        "plot": "After young Riley is uprooted from her Midwest life and moved to San Francisco, her emotions - Joy, Fear, Anger, Disgust and Sadness - conflict on how best to navigate a new city, house, and school.",
        "poster": "https://m.media-amazon.com/images/M/MV5BOTgxMDQwMDk0OF5BMl5BanBnXkFtZTgwNjU5OTg2NDE@._V1_SX300.jpg",
        "imdb_rating": "8.1",
        "imdb_votes": "750,000",
    },
    # --- Modern Classics ---
    {
        "imdb_id": "tt14209916",
        "title": "Everything Everywhere All at Once",
        "year": "2022",
        "rated": "R",
        "runtime": "139 min",
        "genres": ["Action", "Adventure", "Comedy"],
        "director": "Daniel Kwan",
        "actors": ["Michelle Yeoh", "Stephanie Hsu", "Jamie Lee Curtis", "Ke Huy Quan"],
        "plot": "A middle-aged Chinese immigrant is swept up into an insane adventure in which she alone can save existence by exploring other universes and connecting with the lives she could have led.",
        "poster": "https://m.media-amazon.com/images/M/MV5BYTdiOTIyZTQtNmQ1OS00NjZlLWIyMTgtYzk5Y2M3ZDVmMDk1XkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "7.8",
        "imdb_votes": "550,000",
    },
    {
        "imdb_id": "tt15398776",
        "title": "Oppenheimer",
        "year": "2023",
        "rated": "R",
        "runtime": "180 min",
        "genres": ["Biography", "Drama", "History"],
        "director": "Christopher Nolan",
        "actors": ["Cillian Murphy", "Emily Blunt", "Matt Damon", "Robert Downey Jr."],
        "plot": "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.",
        "poster": "https://m.media-amazon.com/images/M/MV5BN2JkMDc5MGQtZjg3YS00NmFiLWIyZmQtZjZjMjc3MmJlZTk2XkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "8.3",
        "imdb_votes": "850,000",
    },
    {
        "imdb_id": "tt1160419",
        "title": "Dune",
        "year": "2021",
        "rated": "PG-13",
        "runtime": "155 min",
        "genres": ["Action", "Adventure", "Drama"],
        "director": "Denis Villeneuve",
        "actors": ["Timothée Chalamet", "Rebecca Ferguson", "Zendaya", "Oscar Isaac"],
        "plot": "A noble family becomes embroiled in a war for control over the galaxy's most valuable asset while its heir becomes troubled by visions of a dark future.",
        "poster": "https://m.media-amazon.com/images/M/MV5BMDQ0NjgyN2YtNWViNS00YjA3LTkxNDktYzFkZTExZGMxZDkxXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "8.0",
        "imdb_votes": "850,000",
    },
    {
        "imdb_id": "tt15239678",
        "title": "Dune: Part Two",
        "year": "2024",
        "rated": "PG-13",
        "runtime": "166 min",
        "genres": ["Action", "Adventure", "Drama"],
        "director": "Denis Villeneuve",
        "actors": ["Timothée Chalamet", "Zendaya", "Austin Butler", "Florence Pugh"],
        "plot": "Paul Atreides unites with the Fremen while on a warpath of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the universe, he endeavors to prevent a terrible future.",
        "poster": "https://m.media-amazon.com/images/M/MV5BN2QyZGU4ZDctOWMzMy00NTc5LThlOGQtODhmNDI1NmY5YzAwXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "8.5",
        "imdb_votes": "650,000",
    },
    {
        "imdb_id": "tt7286456",
        "title": "Joker",
        "year": "2019",
        "rated": "R",
        "runtime": "122 min",
        "genres": ["Crime", "Drama", "Thriller"],
        "director": "Todd Phillips",
        "actors": ["Joaquin Phoenix", "Robert De Niro", "Zazie Beetz", "Frances Conroy"],
        "plot": "During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.",
        "poster": "https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "8.4",
        "imdb_votes": "1,400,000",
    },
    {
        "imdb_id": "tt4633694",
        "title": "Spider-Man: Into the Spider-Verse",
        "year": "2018",
        "rated": "PG",
        "runtime": "117 min",
        "genres": ["Animation", "Action", "Adventure"],
        "director": "Bob Persichetti",
        "actors": ["Shameik Moore", "Jake Johnson", "Hailee Steinfeld", "Mahershala Ali"],
        "plot": "Teen Miles Morales becomes the Spider-Man of his reality, crossing his path with five counterparts from other dimensions to stop a threat for all realities.",
        "poster": "https://m.media-amazon.com/images/M/MV5BMjMwNDkxMTgzOF5BMl5BanBnXkFtZTgwNTkwNTQ3NjM@._V1_SX300.jpg",
        "imdb_rating": "8.4",
        "imdb_votes": "600,000",
    },
    {
        "imdb_id": "tt0482571",
        "title": "The Prestige",
        "year": "2006",
        "rated": "PG-13",
        "runtime": "130 min",
        "genres": ["Drama", "Mystery", "Sci-Fi"],
        "director": "Christopher Nolan",
        "actors": ["Christian Bale", "Hugh Jackman", "Scarlett Johansson", "Michael Caine"],
        "plot": "After a tragic accident, two stage magicians in 1890s London engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.",
        "poster": "https://m.media-amazon.com/images/M/MV5BMjA4NDI0MTIxNF5BMl5BanBnXkFtZTYwNTM0MzY2._V1_SX300.jpg",
        "imdb_rating": "8.5",
        "imdb_votes": "1,400,000",
    },
    {
        "imdb_id": "tt0114369",
        "title": "Se7en",
        "year": "1995",
        "rated": "R",
        "runtime": "127 min",
        "genres": ["Crime", "Drama", "Mystery"],
        "director": "David Fincher",
        "actors": ["Morgan Freeman", "Brad Pitt", "Kevin Spacey", "Gwyneth Paltrow"],
        "plot": "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
        "poster": "https://m.media-amazon.com/images/M/MV5BY2IzNzMxZjctZjUxZi00YzAxLTk3ZjMtODFjOTdhN2IwMTAxXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "8.6",
        "imdb_votes": "1,800,000",
    },
    {
        "imdb_id": "tt0993846",
        "title": "The Wolf of Wall Street",
        "year": "2013",
        "rated": "R",
        "runtime": "180 min",
        "genres": ["Biography", "Comedy", "Crime"],
        "director": "Martin Scorsese",
        "actors": ["Leonardo DiCaprio", "Jonah Hill", "Margot Robbie", "Matthew McConaughey"],
        "plot": "Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption and the federal government.",
        "poster": "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNTk0MF5BMl5BanBnXkFtZTgwNjIyOTg2MDE@._V1_SX300.jpg",
        "imdb_rating": "8.2",
        "imdb_votes": "1,600,000",
    },
    {
        "imdb_id": "tt0114709",
        "title": "Toy Story",
        "year": "1995",
        "rated": "G",
        "runtime": "81 min",
        "genres": ["Animation", "Adventure", "Comedy"],
        "director": "John Lasseter",
        "actors": ["Tom Hanks", "Tim Allen", "Don Rickles", "Jim Varney"],
        "plot": "A cowboy doll is profoundly threatened and jealous when a new spaceman action figure supplants him as top toy in a boy's bedroom.",
        "poster": "https://m.media-amazon.com/images/M/MV5BMDU2ZWJlMjktMTRhMy00ZTA5LWEzNDgtYmNmZTEwZTViZWJkXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "8.3",
        "imdb_votes": "1,000,000",
    },
    {
        "imdb_id": "tt0099685",
        "title": "Goodfellas",
        "year": "1990",
        "rated": "R",
        "runtime": "145 min",
        "genres": ["Biography", "Crime", "Drama"],
        "director": "Martin Scorsese",
        "actors": ["Robert De Niro", "Ray Liotta", "Joe Pesci", "Lorraine Bracco"],
        "plot": "The story of Henry Hill and his life in the mafia, covering his relationship with his wife Karen and his mob partners Jimmy Conway and Tommy DeVito.",
        "poster": "https://m.media-amazon.com/images/M/MV5BY2NkZjEzMDgtN2RjYy00YzM1LWI4ZmQtMjIwYjFjNmI3ZGEwXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "8.7",
        "imdb_votes": "1,200,000",
    },
    {
        "imdb_id": "tt0120815",
        "title": "Saving Private Ryan",
        "year": "1998",
        "rated": "R",
        "runtime": "169 min",
        "genres": ["Drama", "War"],
        "director": "Steven Spielberg",
        "actors": ["Tom Hanks", "Matt Damon", "Tom Sizemore", "Edward Burns"],
        "plot": "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.",
        "poster": "https://m.media-amazon.com/images/M/MV5BZjhkMDM4MWQtZTVjOC00ZDRhLThmYTAtM2I5NzBmNmNlMzI1XkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "8.6",
        "imdb_votes": "1,500,000",
    },
    {
        "imdb_id": "tt0317248",
        "title": "City of God",
        "year": "2002",
        "rated": "R",
        "runtime": "130 min",
        "genres": ["Crime", "Drama"],
        "director": "Fernando Meirelles",
        "actors": ["Alexandre Rodrigues", "Leandro Firmino", "Matheus Nachtergaele", "Phellipe Haagensen"],
        "plot": "In the slums of Rio, two kids' paths diverge as one struggles to become a photographer and the other a drug dealer.",
        "poster": "https://m.media-amazon.com/images/M/MV5BOTMwYjc5ZmItYTFjZC00ZGQ3LTlkNTMtMjZiNTQ1OWIzZDA2XkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "8.6",
        "imdb_votes": "780,000",
    },
    {
        "imdb_id": "tt0457430",
        "title": "Pan's Labyrinth",
        "year": "2006",
        "rated": "R",
        "runtime": "118 min",
        "genres": ["Drama", "Fantasy", "War"],
        "director": "Guillermo del Toro",
        "actors": ["Ivana Baquero", "Ariadna Gil", "Sergi López", "Maribel Verdú"],
        "plot": "In the Falangist Spain of 1944, the bookish young stepdaughter of a sadistic army officer escapes into an eerie but captivating fantasy world.",
        "poster": "https://m.media-amazon.com/images/M/MV5BYzFjMThiMGItOWRlMC00MDI4LThmOGUtYTNkNGRhNjdkMTMzXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "8.2",
        "imdb_votes": "700,000",
    },
    {
        "imdb_id": "tt0119698",
        "title": "Princess Mononoke",
        "year": "1997",
        "rated": "PG-13",
        "runtime": "134 min",
        "genres": ["Animation", "Action", "Adventure"],
        "director": "Hayao Miyazaki",
        "actors": ["Yôji Matsuda", "Yuriko Ishida", "Yûko Tanaka", "Billy Crudup"],
        "plot": "On a journey to find the cure for a Tatarigami's curse, Ashitaka finds himself in the middle of a war between the forest gods and Tatara, a mining colony. In this quest he also meets San, the Mononoke Hime.",
        "poster": "https://m.media-amazon.com/images/M/MV5BNGIzY2IzODQtNThmMi00ZDE4LWI5YzAtNzNlZTM1ZjYyYjUyXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "8.4",
        "imdb_votes": "430,000",
    },
    {
        "imdb_id": "tt1853728",
        "title": "Django Unchained",
        "year": "2012",
        "rated": "R",
        "runtime": "165 min",
        "genres": ["Drama", "Western"],
        "director": "Quentin Tarantino",
        "actors": ["Jamie Foxx", "Christoph Waltz", "Leonardo DiCaprio", "Kerry Washington"],
        "plot": "With the help of a German bounty-hunter, a freed slave sets out to rescue his wife from a brutal plantation owner in Mississippi.",
        "poster": "https://m.media-amazon.com/images/M/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1_SX300.jpg",
        "imdb_rating": "8.5",
        "imdb_votes": "1,700,000",
    },
    {
        "imdb_id": "tt0477348",
        "title": "No Country for Old Men",
        "year": "2007",
        "rated": "R",
        "runtime": "122 min",
        "genres": ["Crime", "Drama", "Thriller"],
        "director": "Joel Coen",
        "actors": ["Tommy Lee Jones", "Javier Bardem", "Josh Brolin", "Woody Harrelson"],
        "plot": "Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and more than two million dollars in cash near the Rio Grande.",
        "poster": "https://m.media-amazon.com/images/M/MV5BMjA5Njk3MjM4OV5BMl5BanBnXkFtZTcwMTc5MTE1MQ@@._V1_SX300.jpg",
        "imdb_rating": "8.2",
        "imdb_votes": "1,000,000",
    },
    {
        "imdb_id": "tt1130884",
        "title": "Shutter Island",
        "year": "2010",
        "rated": "R",
        "runtime": "138 min",
        "genres": ["Mystery", "Thriller"],
        "director": "Martin Scorsese",
        "actors": ["Leonardo DiCaprio", "Emily Mortimer", "Mark Ruffalo", "Ben Kingsley"],
        "plot": "Teddy Daniels and Chuck Aule, two US marshals, are sent to an asylum on a remote island in order to investigate the disappearance of a patient, where Teddy uncovers a shocking truth about the place.",
        "poster": "https://m.media-amazon.com/images/M/MV5BYzhiNDkyNzktNTZmYS00ZTBkLTk2MDAtM2U0YjU1MzgxZjgzXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "8.2",
        "imdb_votes": "1,400,000",
    },
]
