"""Curated movie catalog for offline seeding — modern/recent films (no OMDb API required)."""

SEED_MOVIES = [
    # --- 2024-2025 ---
    {
        "imdb_id": "tt13651794",
        "title": "Nosferatu",
        "year": "2024",
        "rated": "R",
        "runtime": "132 min",
        "genres": ["Drama", "Fantasy", "Horror"],
        "director": "Robert Eggers",
        "actors": ["Bill Skarsgård", "Nicholas Hoult", "Lily-Rose Depp", "Willem Dafoe"],
        "plot": "A gothic tale of obsession between a haunted young woman and the terrifying vampire infatuated with her, causing untold horror in its wake.",
        "poster": "https://m.media-amazon.com/images/M/MV5BNjBjMjA1MjktOTYxNy00NzgyLWIxMmItN2E0MWE3NjA4YTBhXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "7.7",
        "imdb_votes": "250,000",
    },
    {
        "imdb_id": "tt14471268",
        "title": "Anora",
        "year": "2024",
        "rated": "R",
        "runtime": "139 min",
        "genres": ["Comedy", "Drama", "Romance"],
        "director": "Sean Baker",
        "actors": ["Mikey Madison", "Mark Eydelshteyn", "Yura Borisov", "Karren Karagulian"],
        "plot": "A young sex worker from Brooklyn gets her chance at a Cinderella story when she meets and impulsively marries the son of a Russian oligarch. Once the news reaches Russia, her fairytale is threatened.",
        "poster": "https://m.media-amazon.com/images/M/MV5BNjBjNGQ4MDItYjc0NS00NjVkLTk2MjEtYzUwNjczZjcxMjI3XkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "7.8",
        "imdb_votes": "120,000",
    },
    {
        "imdb_id": "tt28607951",
        "title": "Conclave",
        "year": "2024",
        "rated": "PG",
        "runtime": "120 min",
        "genres": ["Drama", "Mystery", "Thriller"],
        "director": "Edward Berger",
        "actors": ["Ralph Fiennes", "Stanley Tucci", "John Lithgow", "Isabella Rossellini"],
        "plot": "Following the unexpected death of the Pope, Cardinal Lawrence is tasked with managing the secretive conclave to elect a new pope, uncovering dark secrets along the way.",
        "poster": "https://m.media-amazon.com/images/M/MV5BYWI2ZWI1YzktZGQ5NS00MWQ1LThiNDItMGNhNTc2ODI4NzhhXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "7.6",
        "imdb_votes": "140,000",
    },
    {
        "imdb_id": "tt12747748",
        "title": "The Substance",
        "year": "2024",
        "rated": "R",
        "runtime": "140 min",
        "genres": ["Comedy", "Drama", "Horror"],
        "director": "Coralie Fargeat",
        "actors": ["Demi Moore", "Margaret Qualley", "Dennis Quaid", "Hugo Diego Garcia"],
        "plot": "A fading celebrity takes a black-market drug that temporarily creates a younger, better version of herself.",
        "poster": "https://m.media-amazon.com/images/M/MV5BYTFkMzg0OWEtNWIzZC00MjJhLTkzN2EtYzBhZTdkMGIzMGI2XkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "7.3",
        "imdb_votes": "200,000",
    },
    {
        "imdb_id": "tt28015403",
        "title": "The Brutalist",
        "year": "2024",
        "rated": "R",
        "runtime": "215 min",
        "genres": ["Drama"],
        "director": "Brady Corbet",
        "actors": ["Adrien Brody", "Felicity Jones", "Guy Pearce", "Joe Alwyn"],
        "plot": "A visionary architect escapes postwar Europe and resettles in America, where his talent is recognized by a wealthy industrialist whose offer will change the course of his life.",
        "poster": "https://m.media-amazon.com/images/M/MV5BYWU0ZTVkZjctNWE2Ny00ZjUxLTgzZTctMTExOGViMTYzNDI2XkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "7.5",
        "imdb_votes": "50,000",
    },
    {
        "imdb_id": "tt23849204",
        "title": "A Real Pain",
        "year": "2024",
        "rated": "R",
        "runtime": "90 min",
        "genres": ["Comedy", "Drama"],
        "director": "Jesse Eisenberg",
        "actors": ["Jesse Eisenberg", "Kieran Culkin", "Will Sharpe", "Jennifer Grey"],
        "plot": "Mismatched cousins reunite for a tour through Poland to honor their beloved grandmother.",
        "poster": "https://m.media-amazon.com/images/M/MV5BNDM3MTU2NDMtYTJhZi00MjhkLWI2MWItNTU3YjIwMDY4YTcyXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "7.4",
        "imdb_votes": "80,000",
    },
    {
        "imdb_id": "tt14998742",
        "title": "Challengers",
        "year": "2024",
        "rated": "R",
        "runtime": "131 min",
        "genres": ["Drama", "Romance", "Sport"],
        "director": "Luca Guadagnino",
        "actors": ["Zendaya", "Josh O'Connor", "Mike Faist", "Darnell Appling"],
        "plot": "Tashi, a former tennis prodigy turned coach, transforms her husband from a mediocre player into a world-famous champion. Their marriage becomes a complex game when he faces off against his former best friend.",
        "poster": "https://m.media-amazon.com/images/M/MV5BNjA0NzUwMTAtMWI4OC00MjM3LThlYWQtOTAzMDdmOGI2NDUzXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "7.6",
        "imdb_votes": "200,000",
    },
    {
        "imdb_id": "tt15239678",
        "title": "Dune: Part Two",
        "year": "2024",
        "rated": "PG-13",
        "runtime": "166 min",
        "genres": ["Action", "Adventure", "Drama"],
        "director": "Denis Villeneuve",
        "actors": ["Timoth\u00e9e Chalamet", "Zendaya", "Austin Butler", "Florence Pugh"],
        "plot": "Paul Atreides unites with the Fremen while on a warpath of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the universe, he endeavors to prevent a terrible future.",
        "poster": "https://m.media-amazon.com/images/M/MV5BN2QyZGU4ZDctOWMzMy00NTc5LThlOGQtODhmNDI1NmY5YzAwXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "8.5",
        "imdb_votes": "650,000",
    },
    {
        "imdb_id": "tt21235248",
        "title": "Godzilla Minus One",
        "year": "2023",
        "rated": "PG-13",
        "runtime": "124 min",
        "genres": ["Action", "Adventure", "Drama"],
        "director": "Takashi Yamazaki",
        "actors": ["Ry\u016bnosuke Kamiki", "Minami Hamabe", "Y\u016bki Yamada", "Munetaka Aoki"],
        "plot": "Post-war Japan is at its lowest point when a new crisis emerges in the form of a giant monster, baptized in the horror of the atomic bomb.",
        "poster": "https://m.media-amazon.com/images/M/MV5BMDI0NWJhNzAtNjAyZi00MjU4LWJhZWItYTZhYjZhODk0NGRiXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "7.8",
        "imdb_votes": "150,000",
    },
    # --- 2023 ---
    {
        "imdb_id": "tt15398776",
        "title": "Oppenheimer",
        "year": "2023",
        "rated": "R",
        "runtime": "180 min",
        "genres": ["Biography", "Drama", "History"],
        "director": "Christopher Nolan",
        "actors": ["Cillian Murphy", "Emily Blunt", "Matt Damon", "Robert Downey Jr."],
        "plot": "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.",
        "poster": "https://m.media-amazon.com/images/M/MV5BN2JkMDc5MGQtZjg3YS00NmFiLWIyZmQtZjZjMjc3MmJlZTk2XkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "8.3",
        "imdb_votes": "850,000",
    },
    {
        "imdb_id": "tt1517268",
        "title": "Barbie",
        "year": "2023",
        "rated": "PG-13",
        "runtime": "114 min",
        "genres": ["Adventure", "Comedy", "Fantasy"],
        "director": "Greta Gerwig",
        "actors": ["Margot Robbie", "Ryan Gosling", "America Ferrera", "Kate McKinnon"],
        "plot": "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
        "poster": "https://m.media-amazon.com/images/M/MV5BNjU3N2QxNzYtMjk1NC00MTc4LTk1NTQtMmUxNTljM2I0NDA5XkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "6.8",
        "imdb_votes": "600,000",
    },
    {
        "imdb_id": "tt5537002",
        "title": "Killers of the Flower Moon",
        "year": "2023",
        "rated": "R",
        "runtime": "206 min",
        "genres": ["Crime", "Drama", "History"],
        "director": "Martin Scorsese",
        "actors": ["Leonardo DiCaprio", "Robert De Niro", "Lily Gladstone", "Jesse Plemons"],
        "plot": "Members of the Osage tribe in the United States are murdered under mysterious circumstances in the 1920s, sparking a major FBI investigation involving J. Edgar Hoover.",
        "poster": "https://m.media-amazon.com/images/M/MV5BMjE4ZTZlNDAtM2Q3YS00YjFhLThjN2UtOGIzZGUwMmVlNTVmXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "7.6",
        "imdb_votes": "350,000",
    },
    {
        "imdb_id": "tt13238346",
        "title": "Past Lives",
        "year": "2023",
        "rated": "PG-13",
        "runtime": "105 min",
        "genres": ["Drama", "Romance"],
        "director": "Celine Song",
        "actors": ["Greta Lee", "Teo Yoo", "John Magaro", "Moon Seung-ah"],
        "plot": "Nora and Hae Sung, two deeply connected childhood friends, are wrenched apart after Nora's family emigrates from South Korea. Twenty years later, they are reunited for one fateful week.",
        "poster": "https://m.media-amazon.com/images/M/MV5BNzA3MGE5MmMtMjdhZi00NTY0LWE2NTUtYTk2NTFhN2RjNGRhXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "7.8",
        "imdb_votes": "120,000",
    },
    {
        "imdb_id": "tt11304740",
        "title": "The Holdovers",
        "year": "2023",
        "rated": "R",
        "runtime": "133 min",
        "genres": ["Comedy", "Drama"],
        "director": "Alexander Payne",
        "actors": ["Paul Giamatti", "Da'Vine Joy Randolph", "Dominic Sessa", "Carrie Preston"],
        "plot": "A cranky history teacher at a remote prep school is forced to remain on campus over the holidays with a troubled student who has no place to go.",
        "poster": "https://m.media-amazon.com/images/M/MV5BNDc2MzNkMjMtZDY5NC00NmQ0LWI1NjctZjRhNWIzZDcwNmUzXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "7.9",
        "imdb_votes": "200,000",
    },
    {
        "imdb_id": "tt14444726",
        "title": "The Banshees of Inisherin",
        "year": "2022",
        "rated": "R",
        "runtime": "114 min",
        "genres": ["Comedy", "Drama"],
        "director": "Martin McDonagh",
        "actors": ["Colin Farrell", "Brendan Gleeson", "Kerry Condon", "Barry Keoghan"],
        "plot": "Two lifelong friends find themselves at an impasse when one abruptly ends their relationship, with alarming consequences for both of them.",
        "poster": "https://m.media-amazon.com/images/M/MV5BM2NlZDI0ZDktNTg5OS00ZjQ1LWIyNTktNTM5M2IxZmNjNGFiXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "7.7",
        "imdb_votes": "300,000",
    },
    # --- 2022 ---
    {
        "imdb_id": "tt14209916",
        "title": "Everything Everywhere All at Once",
        "year": "2022",
        "rated": "R",
        "runtime": "139 min",
        "genres": ["Action", "Adventure", "Comedy"],
        "director": "Daniel Kwan",
        "actors": ["Michelle Yeoh", "Stephanie Hsu", "Jamie Lee Curtis", "Ke Huy Quan"],
        "plot": "A middle-aged Chinese immigrant is swept up into an insane adventure in which she alone can save existence by exploring other universes and connecting with the lives she could have led.",
        "poster": "https://m.media-amazon.com/images/M/MV5BYTdiOTIyZTQtNmQ1OS00NjZlLWIyMTgtYzk5Y2M3ZDVmMDk1XkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "7.8",
        "imdb_votes": "550,000",
    },
    {
        "imdb_id": "tt15314262",
        "title": "All Quiet on the Western Front",
        "year": "2022",
        "rated": "R",
        "runtime": "148 min",
        "genres": ["Action", "Drama", "War"],
        "director": "Edward Berger",
        "actors": ["Felix Kammerer", "Albrecht Schuch", "Aaron Hilmer", "Moritz Klaus"],
        "plot": "A young German soldier's terrifying experiences and disillusionment in the trenches during World War I.",
        "poster": "https://m.media-amazon.com/images/M/MV5BMzM1YTI4ZjYtODBiNi00ZmZlLWI4NzctMmExYWM0NjFiNTczXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "7.8",
        "imdb_votes": "350,000",
    },
    {
        "imdb_id": "tt9764362",
        "title": "The Menu",
        "year": "2022",
        "rated": "R",
        "runtime": "107 min",
        "genres": ["Comedy", "Horror", "Thriller"],
        "director": "Mark Mylod",
        "actors": ["Ralph Fiennes", "Anya Taylor-Joy", "Nicholas Hoult", "Hong Chau"],
        "plot": "A young couple travels to a coastal island to eat at an exclusive restaurant where the chef has prepared a lavish menu, with some shocking surprises.",
        "poster": "https://m.media-amazon.com/images/M/MV5BMzQ1ZWUyNjUtYzk3NS00MjVkLTk4NjgtYzNhNWFkZGM4NjFiXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "7.2",
        "imdb_votes": "350,000",
    },
    {
        "imdb_id": "tt17351924",
        "title": "Saltburn",
        "year": "2023",
        "rated": "R",
        "runtime": "131 min",
        "genres": ["Comedy", "Drama", "Thriller"],
        "director": "Emerald Fennell",
        "actors": ["Barry Keoghan", "Jacob Elordi", "Rosamund Pike", "Richard E. Grant"],
        "plot": "A student at Oxford University finds himself drawn into the world of a charming and aristocratic classmate, who invites him to his eccentric family's sprawling estate.",
        "poster": "https://m.media-amazon.com/images/M/MV5BZmI4ZjliYjktNDBkZC00ZmNlLTgyODktODgxMTg3OGY5OGM1XkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "7.0",
        "imdb_votes": "300,000",
    },
    {
        "imdb_id": "tt11866324",
        "title": "Poor Things",
        "year": "2023",
        "rated": "R",
        "runtime": "141 min",
        "genres": ["Comedy", "Drama", "Romance"],
        "director": "Yorgos Lanthimos",
        "actors": ["Emma Stone", "Mark Ruffalo", "Willem Dafoe", "Ramy Youssef"],
        "plot": "The incredible tale about the fantastical evolution of Bella Baxter, a young woman brought back to life by the brilliant and unorthodox scientist Dr. Godwin Baxter.",
        "poster": "https://m.media-amazon.com/images/M/MV5BNGIyYWMzNjktNDE3MC00MDE2LTk0ZDItZTdlODcwNDM0NTAyXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "7.8",
        "imdb_votes": "300,000",
    },
    # --- 2021 ---
    {
        "imdb_id": "tt1160419",
        "title": "Dune",
        "year": "2021",
        "rated": "PG-13",
        "runtime": "155 min",
        "genres": ["Action", "Adventure", "Drama"],
        "director": "Denis Villeneuve",
        "actors": ["Timoth\u00e9e Chalamet", "Rebecca Ferguson", "Zendaya", "Oscar Isaac"],
        "plot": "A noble family becomes embroiled in a war for control over the galaxy's most valuable asset while its heir becomes troubled by visions of a dark future.",
        "poster": "https://m.media-amazon.com/images/M/MV5BMDQ0NjgyN2YtNWViNS00YjA3LTkxNDktYzFkZTExZGMxZDkxXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "8.0",
        "imdb_votes": "850,000",
    },
    {
        "imdb_id": "tt10366206",
        "title": "John Wick: Chapter 4",
        "year": "2023",
        "rated": "R",
        "runtime": "169 min",
        "genres": ["Action", "Crime", "Thriller"],
        "director": "Chad Stahelski",
        "actors": ["Keanu Reeves", "Laurence Fishburne", "George Georgiou", "Lance Reddick"],
        "plot": "John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe.",
        "poster": "https://m.media-amazon.com/images/M/MV5BMDExZGMyOTMtMDgyYi00NGIwLWJhMTEtOTdkZGFjNmZiMTEwXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "7.7",
        "imdb_votes": "450,000",
    },
    {
        "imdb_id": "tt1745960",
        "title": "Top Gun: Maverick",
        "year": "2022",
        "rated": "PG-13",
        "runtime": "130 min",
        "genres": ["Action", "Drama"],
        "director": "Joseph Kosinski",
        "actors": ["Tom Cruise", "Jennifer Connelly", "Miles Teller", "Val Kilmer"],
        "plot": "After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past when he leads TOP GUN's elite graduates on a mission that demands the ultimate sacrifice.",
        "poster": "https://m.media-amazon.com/images/M/MV5BYzBkMjMzMzktZGI5Mi00NjFhLTlmNjAtNTQ5MjEzYzNmMjI5XkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "8.2",
        "imdb_votes": "700,000",
    },
    {
        "imdb_id": "tt10872600",
        "title": "Spider-Man: No Way Home",
        "year": "2021",
        "rated": "PG-13",
        "runtime": "148 min",
        "genres": ["Action", "Adventure", "Fantasy"],
        "director": "Jon Watts",
        "actors": ["Tom Holland", "Zendaya", "Benedict Cumberbatch", "Jacob Batalon"],
        "plot": "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
        "poster": "https://m.media-amazon.com/images/M/MV5BMmFiZGZjMmEtMTA0Ni00MzA2LTljMTYtZGI2MGJmZWYzZTQ2XkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "8.2",
        "imdb_votes": "900,000",
    },
    {
        "imdb_id": "tt9362722",
        "title": "Spider-Man: Across the Spider-Verse",
        "year": "2023",
        "rated": "PG",
        "runtime": "140 min",
        "genres": ["Animation", "Action", "Adventure"],
        "director": "Joaquim Dos Santos",
        "actors": ["Shameik Moore", "Hailee Steinfeld", "Brian Tyree Henry", "Luna Lauren Velez"],
        "plot": "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence. When the heroes clash on how to handle a new threat, Miles must redefine what it means to be a hero.",
        "poster": "https://m.media-amazon.com/images/M/MV5BNThiZjA3MjItZGY5Ni00ZjRhLWEzNzAtYTU4NjkyZjRlMGQzXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "8.6",
        "imdb_votes": "400,000",
    },
    {
        "imdb_id": "tt6856396",
        "title": "The Boy and the Heron",
        "year": "2023",
        "rated": "PG-13",
        "runtime": "124 min",
        "genres": ["Animation", "Adventure", "Drama"],
        "director": "Hayao Miyazaki",
        "actors": ["Soma Santoki", "Masaki Suda", "Takuya Kimura", "Aimyon"],
        "plot": "A young boy named Mahito yearning for his mother ventures into a world shared by the living and the dead. There, death comes to an end, and life finds a new beginning.",
        "poster": "https://m.media-amazon.com/images/M/MV5BZjZkNTg1MGItMjYzNi00YTBhLWE1MTQtOTQ4MDFkZjJmNjFhXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "7.5",
        "imdb_votes": "100,000",
    },
    {
        "imdb_id": "tt21692408",
        "title": "Society of the Snow",
        "year": "2023",
        "rated": "R",
        "runtime": "144 min",
        "genres": ["Adventure", "Biography", "Drama"],
        "director": "J.A. Bayona",
        "actors": ["Enzo Vogrincic", "Matías Recalt", "Agustín Pardella", "Felipe González Otaño"],
        "plot": "The story of the Uruguayan rugby team's 1972 plane crash in the Andes and their extraordinary fight for survival.",
        "poster": "https://m.media-amazon.com/images/M/MV5BNzE1YzUzODgtNjc3Ni00MDkzLWI4NGItZGQ5NjQ3Y2Y5NTRjXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "7.8",
        "imdb_votes": "200,000",
    },
    {
        "imdb_id": "tt13655120",
        "title": "The Iron Claw",
        "year": "2023",
        "rated": "R",
        "runtime": "132 min",
        "genres": ["Biography", "Drama", "Sport"],
        "director": "Sean Durkin",
        "actors": ["Zac Efron", "Jeremy Allen White", "Harris Dickinson", "Maura Tierney"],
        "plot": "The true story of the inseparable Von Erich brothers, who made history in the intensely competitive world of professional wrestling in the early 1980s.",
        "poster": "https://m.media-amazon.com/images/M/MV5BMjAyMTk2MTQ3Ml5BMl5BanBnXkFtZTcwNTUyMTMyMw@@._V1_SX300.jpg",
        "imdb_rating": "7.6",
        "imdb_votes": "120,000",
    },
    {
        "imdb_id": "tt12037194",
        "title": "The Whale",
        "year": "2022",
        "rated": "R",
        "runtime": "117 min",
        "genres": ["Drama"],
        "director": "Darren Aronofsky",
        "actors": ["Brendan Fraser", "Sadie Sink", "Hong Chau", "Ty Simpkins"],
        "plot": "A reclusive English teacher suffering from severe obesity attempts to reconnect with his estranged teenage daughter for one last chance at redemption.",
        "poster": "https://m.media-amazon.com/images/M/MV5BZDQ4Njg1OTctZDhjNi00MDI3LWFjNGEtZTk4N2JjZjAxNzUzXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "7.7",
        "imdb_votes": "250,000",
    },
    {
        "imdb_id": "tt14039582",
        "title": "Drive My Car",
        "year": "2021",
        "rated": "NR",
        "runtime": "179 min",
        "genres": ["Drama"],
        "director": "Ryûsuke Hamaguchi",
        "actors": ["Hidetoshi Nishijima", "Tôko Miura", "Reika Kirishima", "Park Yu-rim"],
        "plot": "A renowned stage actor and director learns to face the haunting truths of his past when he is forced to confront deep loss during the production of a play.",
        "poster": "https://m.media-amazon.com/images/M/MV5BOGIxZDU5YjMtNjBhYy00MTY3LWE5MzYtZDMxNmQyMmI0MzA3XkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "7.6",
        "imdb_votes": "70,000",
    },
    # --- 2020-2019 ---
    {
        "imdb_id": "tt8579674",
        "title": "1917",
        "year": "2019",
        "rated": "R",
        "runtime": "119 min",
        "genres": ["Action", "Drama", "War"],
        "director": "Sam Mendes",
        "actors": ["Dean-Charles Chapman", "George MacKay", "Daniel Mays", "Colin Firth"],
        "plot": "Two young British soldiers during World War I are given an impossible mission: deliver a message deep in enemy territory that will stop 1,600 men from walking into a deadly trap.",
        "poster": "https://m.media-amazon.com/images/M/MV5BOTdmNTFjNDEtNzg0My00ZjkxLTg1ZDAtZTdkMDc2ZmFiNWQ1XkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "8.2",
        "imdb_votes": "600,000",
    },
    {
        "imdb_id": "tt4633694",
        "title": "Spider-Man: Into the Spider-Verse",
        "year": "2018",
        "rated": "PG",
        "runtime": "117 min",
        "genres": ["Animation", "Action", "Adventure"],
        "director": "Bob Persichetti",
        "actors": ["Shameik Moore", "Jake Johnson", "Hailee Steinfeld", "Mahershala Ali"],
        "plot": "Teen Miles Morales becomes the Spider-Man of his reality, crossing his path with five counterparts from other dimensions to stop a threat for all realities.",
        "poster": "https://m.media-amazon.com/images/M/MV5BMjMwNDkxMTgzOF5BMl5BanBnXkFtZTgwNTkwNTQ3NjM@._V1_SX300.jpg",
        "imdb_rating": "8.4",
        "imdb_votes": "600,000",
    },
    {
        "imdb_id": "tt6751668",
        "title": "Parasite",
        "year": "2019",
        "rated": "R",
        "runtime": "132 min",
        "genres": ["Comedy", "Drama", "Thriller"],
        "director": "Bong Joon Ho",
        "actors": ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong", "Choi Woo-shik"],
        "plot": "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
        "poster": "https://m.media-amazon.com/images/M/MV5BYjk1Y2U4MjQtY2ZiNS00OWQyLWI3MmYtZWUwNmRjYWRiNWNhXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "8.5",
        "imdb_votes": "900,000",
    },
    {
        "imdb_id": "tt7286456",
        "title": "Joker",
        "year": "2019",
        "rated": "R",
        "runtime": "122 min",
        "genres": ["Crime", "Drama", "Thriller"],
        "director": "Todd Phillips",
        "actors": ["Joaquin Phoenix", "Robert De Niro", "Zazie Beetz", "Frances Conroy"],
        "plot": "During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.",
        "poster": "https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "8.4",
        "imdb_votes": "1,400,000",
    },
    {
        "imdb_id": "tt6263850",
        "title": "The Fabelmans",
        "year": "2022",
        "rated": "PG-13",
        "runtime": "151 min",
        "genres": ["Drama"],
        "director": "Steven Spielberg",
        "actors": ["Michelle Williams", "Gabriel LaBelle", "Paul Dano", "Seth Rogen"],
        "plot": "Growing up in post-World War II era Arizona, young Sammy Fabelman aspires to become a filmmaker as he reaches adolescence, but soon discovers a shattering family secret.",
        "poster": "https://m.media-amazon.com/images/M/MV5BZWI1YTMwMjEtODRiNy00OTc4LThmMzktODBiYWMzZjRjZmIwXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "7.5",
        "imdb_votes": "150,000",
    },
    {
        "imdb_id": "tt5090568",
        "title": "Tár",
        "year": "2022",
        "rated": "R",
        "runtime": "158 min",
        "genres": ["Drama", "Music"],
        "director": "Todd Field",
        "actors": ["Cate Blanchett", "Noémie Merlant", "Nina Hoss", "Sophie Kauer"],
        "plot": "Set in the international world of Western classical music, the film centers on Lydia Tár, widely considered one of the greatest living composer-conductors and the first-ever female music director of a major German orchestra.",
        "poster": "https://m.media-amazon.com/images/M/MV5BMjkxNTMzNzEtMDhlYy00ZmEyLWEwMzAtOGJmMjA1NmE2YTZmXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "7.4",
        "imdb_votes": "130,000",
    },
    {
        "imdb_id": "tt14230458",
        "title": "Anatomy of a Fall",
        "year": "2023",
        "rated": "R",
        "runtime": "152 min",
        "genres": ["Crime", "Drama", "Thriller"],
        "director": "Justine Triet",
        "actors": ["Sandra Hüller", "Swann Arlaud", "Milo Machado Graner", "Antoine Reinartz"],
        "plot": "A woman is suspected of her husband's murder, and their blind son faces a moral dilemma as the only witness.",
        "poster": "https://m.media-amazon.com/images/M/MV5BMDBjYjhjN2ItMzZiOS00ZGI0LWI4MmMtMjA5YzY2NjhjNWI2XkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "7.7",
        "imdb_votes": "120,000",
    },
    {
        "imdb_id": "tt3170832",
        "title": "Room",
        "year": "2015",
        "rated": "R",
        "runtime": "118 min",
        "genres": ["Drama", "Thriller"],
        "director": "Lenny Abrahamson",
        "actors": ["Brie Larson", "Jacob Tremblay", "Sean Bridgers", "Wendy Crewson"],
        "plot": "Held captive for 7 years in an enclosed space, a woman and her young son finally gain their freedom, allowing the boy to experience the outside world for the first time.",
        "poster": "https://m.media-amazon.com/images/M/MV5BMjE4NzgzNzEwMl5BMl5BanBnXkFtZTgwMTMzMDE0NjE@._V1_SX300.jpg",
        "imdb_rating": "8.1",
        "imdb_votes": "450,000",
    },
    {
        "imdb_id": "tt2084970",
        "title": "The Imitation Game",
        "year": "2014",
        "rated": "PG-13",
        "runtime": "114 min",
        "genres": ["Biography", "Drama", "Thriller"],
        "director": "Morten Tyldum",
        "actors": ["Benedict Cumberbatch", "Keira Knightley", "Matthew Goode", "Rory Kinnear"],
        "plot": "During World War II, the English mathematical genius Alan Turing tries to crack the German Enigma code with help from fellow mathematicians while dealing with his troubled personal life.",
        "poster": "https://m.media-amazon.com/images/M/MV5BOTgwMzFiMWYtZDhlNS00ODNkLWJiODAtZDVhNzgyNzJhYjQ4L2ltYWdlXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "8.0",
        "imdb_votes": "800,000",
    },
    {
        "imdb_id": "tt2119532",
        "title": "Hacksaw Ridge",
        "year": "2016",
        "rated": "R",
        "runtime": "139 min",
        "genres": ["Biography", "Drama", "History"],
        "director": "Mel Gibson",
        "actors": ["Andrew Garfield", "Sam Worthington", "Luke Bracey", "Teresa Palmer"],
        "plot": "World War II Army Medic Desmond T. Doss, who served during the Battle of Okinawa, refuses to kill people and becomes the first man in American history to receive the Medal of Honor without firing a shot.",
        "poster": "https://m.media-amazon.com/images/M/MV5BMjQ1NjM3MTUxNV5BMl5BanBnXkFtZTgwMDc5MTY5OTE@._V1_SX300.jpg",
        "imdb_rating": "8.1",
        "imdb_votes": "550,000",
    },
    {
        "imdb_id": "tt1950186",
        "title": "Ford v Ferrari",
        "year": "2019",
        "rated": "PG-13",
        "runtime": "152 min",
        "genres": ["Action", "Biography", "Drama"],
        "director": "James Mangold",
        "actors": ["Matt Damon", "Christian Bale", "Jon Bernthal", "Caitriona Balfe"],
        "plot": "American car designer Carroll Shelby and fearless British driver Ken Miles battle corporate interference and the laws of physics to build a revolutionary car for Ford in order to defeat Ferrari at the 1966 24 Hours of Le Mans.",
        "poster": "https://m.media-amazon.com/images/M/MV5BM2UwMDVmMDItM2I2Yi00NGZmLTk4ZTUtY2JjNTQ3OGQ5ZjM2XkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "8.1",
        "imdb_votes": "450,000",
    },
    {
        "imdb_id": "tt9603212",
        "title": "Mission: Impossible - Dead Reckoning Part One",
        "year": "2023",
        "rated": "PG-13",
        "runtime": "163 min",
        "genres": ["Action", "Adventure", "Thriller"],
        "director": "Christopher McQuarrie",
        "actors": ["Tom Cruise", "Hayley Atwell", "Ving Rhames", "Simon Pegg"],
        "plot": "Ethan Hunt and his IMF team must track down a dangerous weapon before it falls into the wrong hands.",
        "poster": "https://m.media-amazon.com/images/M/MV5BYzFiZjc1YzctMDY3Zi00NGE5LTlmNWEtN2M2NGNkZDMzODMxXkEyXkFqcGc@._V1_SX300.jpg",
        "imdb_rating": "7.7",
        "imdb_votes": "350,000",
    },
]
